# A descriptive name for your workflow
name: Python Test and Lint Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the "main" branch
  push:
    branches: [ "main" ]
  # Also triggers the workflow on pull requests to the "main" branch
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up a Python environment for use in the workflow
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      # This step uses pip to install the packages listed in your requirements.txt
      # and installs your project in "editable" mode, which is necessary for testing.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      # Step 4: Run the tests using pytest
      # This command will execute your test suite. If any test fails, this step will fail,
      # and the entire workflow run will be marked as failed.
      - name: Run tests with pytest
        run: |
          python -m pytest